name: Publish Cocoapods

on:
  pull_request:
    types: 
      - closed
    branches:
      - 'main'

jobs:
  publish_cocoapods:
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'release/')
    runs-on: macos-12
    steps:
    - name: Repository checkout
      uses: actions/checkout@v3
    - name: Deploy to Cocoapods
      run: |
        set -eo pipefail
        pod lib lint --allow-warnings --verbose
        pod trunk push --allow-warnings --verbose
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}